language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - 14
git:
  depth: 3
scripts:
  - yarn test
notifications:
  email:
    recipients:
      - lesterpaz99@gmail.com
on_success: always
on_failure: always
deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key: $API_KEY_HEROKU
  app: platzi-store2-backend
  on:
    repo: lesterpaz99/platzi-store-backend
